name: Testing pipeline
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      -
        name: Setup installation requirements
        run: |
          pip install --upgrade pip
          pip install coverage pytest
          pip install -e .
          python install_coverage_subprocess_pth.py
          echo "COVERAGE_PROCESS_START=${{ github.workspace }}/.coveragerc" >> $GITHUB_ENV
      -
        name: Test
        run: |
          echo "${{ env.COVERAGE_PROCESS_START }}"
          coverage run -m pytest --color=yes test/
          coverage combine
          coverage xml -o codecoverage.xml
      -
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with: # no token required for public repos
          fail_ci_if_error: true
          files: ./codecoverage.xml
